/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import clases.Empleado;
import control.ControlEmpleado;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author teenc
 */
public class EmpleadoFrm extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmpleadoFrm
     */
    Empleado e = null;
    ControlEmpleado ce = new ControlEmpleado();

    public EmpleadoFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmailPersona = new javax.swing.JTextField();
        txtEmailEmpresa = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Identificacion");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Telefono");

        jLabel5.setText("E-mail personal");

        jLabel6.setText("E-mail empresa");

        jLabel7.setText("Cargo");

        jLabel8.setText("Estado");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnActualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellido)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtEmailPersona)
                                    .addComponent(txtEmailEmpresa)
                                    .addComponent(txtCargo)
                                    .addComponent(txtEstado)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnLimpiar)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtEmailPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevo)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Accion click crear nuevo registro
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        //VAlidar casillas vacias
        if (validarVacio()) {
            limpiarFormulario();
            JOptionPane.showMessageDialog(null, "Complete el formulario");
        } else {

            try {

                //Se crea la clase para la consulta
                e = new Empleado("", txtCargo.getText(), txtEmailEmpresa.getText(), txtEstado.getText(),
                        txtNombre.getText(), txtApellido.getText(), txtTelefono.getText(), txtEmailPersona.getText(),
                        txtIdentificacion.getText());

                //Se realiza consulta
                ce.nuevoEmpleado(e);
                
                JOptionPane.showMessageDialog(null, "Se creo registro");
            } catch (HeadlessException ex) {

                Logger.getLogger(EmpleadoFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    //Funcion buscar registro
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        //Condicional de casillas vacias
        if (txtIdentificacion.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Llene todos los valores del Formulario");
        } else {

            buscarRegistro();
            if (!buscarRegistro()) {
                
                JOptionPane.showMessageDialog(null, "Registro no encontrado");
                
            } else {

                //Configuraciones de seguridad
                txtIdentificacion.setEnabled(false);
                btnActualizar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnNuevo.setEnabled(false);

            }
        }
        limpiarFormulario();
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Accion click boton eliminar
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        //Verificacion casillas vacias
        if (validarVacio()) {

            JOptionPane.showMessageDialog(null, "LLeno todos los valores del formulario");
        } else {

            //Mensaje para confirmacion
            int confirmacion = alertaConsulta("eliminara");

            //Decision frente a confirmacion
            switch (confirmacion) {
                case 0 -> {

                    //Se realiza consulta
                    eliminarEmpleado();
                    JOptionPane.showMessageDialog(null, "Se elimino el registro");
                }
                case 1 -> {
                    break;
                }
                default ->
                    throw new AssertionError();
            }
        }
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    //Accion click boton actualizar
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        //Verificacion vacios
        if (validarVacio()) {

            JOptionPane.showMessageDialog(null, "LLene todos los valores del formulario");
        } else {

            //Alerta de confirmacion
            int confirmacion = alertaConsulta("actualizara");

            //Decision segun confirmacion
            switch (confirmacion) {
                case 0 -> {

                    //Se realiza consulta
                    actualizarEmpleado();
                    JOptionPane.showMessageDialog(null, "Se actualizo el registro");
                }
                case 1 -> {
                    break;
                }
                default ->
                    throw new AssertionError();
            }
        }
        limpiarFormulario();
    }//GEN-LAST:event_btnActualizarActionPerformed

    //Accion click boton limpiar
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtEmailEmpresa;
    private javax.swing.JTextField txtEmailPersona;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public boolean validarVacio() {

        return txtApellido.getText().equals("") || txtCargo.getText().equals("") || txtEmailEmpresa.getText().equals("")
                || txtEmailPersona.getText().equals("") || txtEstado.getText().equals("") || txtIdentificacion.getText().equals("")
                || txtNombre.getText().equals("") || txtTelefono.getText().equals("");

    }

    //Se restablece el formulario
    public void limpiarFormulario() {

        //Se limpian casillas
        txtApellido.setText("");
        txtCargo.setText("");
        txtEmailEmpresa.setText("");
        txtEmailPersona.setText("");
        txtEstado.setText("");
        txtIdentificacion.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        //Se habilitan/deshabiliatan casillas
        txtApellido.setEnabled(true);
        txtCargo.setEnabled(true);
        txtEmailEmpresa.setEnabled(true);
        txtEmailPersona.setEnabled(true);
        txtEstado.setEnabled(true);
        txtIdentificacion.setEnabled(true);
        txtNombre.setEnabled(true);
        txtTelefono.setEnabled(true);
        //Se habiltan/deshabilitan botones
        btnBuscar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnActualizar.setEnabled(false);

    }

    //Alerta de confirmacion
    public int alertaConsulta(String accion) {

        return JOptionPane.showInternalConfirmDialog(null, "Se :" + accion
                + "Identificacion :" + txtIdentificacion.getText() + "\n"
                + " Nombre :" + txtNombre.getText() + "\n"
                + " Apellido :" + txtApellido.getText() + "\n"
                + " Telefono :" + txtTelefono.getText() + "\n"
                + " Cargo :" + txtCargo.getText() + "\n"
                + " Estado :" + txtEstado.getText() + "\n"
                + " E-mail Per.:" + txtEmailPersona.getText() + "\n"
                + " E-Mail Emp.: " + txtEmailEmpresa.getText(),
                "Confirmacion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

    }

    //Funcion buscar registro
    public boolean buscarRegistro() {
        try {

            //Se realiza consulta
            e = ce.buscarEmpleado(txtIdentificacion.getText());

            //Decision segun respuesta
            if (e != null) {

                //Se asignan valores a las casillas del formulario
                txtIdentificacion.setText(e.getIdentificacionPersona());
                txtNombre.setText(e.getNombrePersona());
                txtApellido.setText(e.getApellido());
                txtTelefono.setText(e.getTelefonoPersona());
                txtEmailPersona.setText(e.getMailPersona());
                txtEmailEmpresa.setText(e.getMailEmpresa());
                txtCargo.setText(e.getCargo());
                txtEstado.setText(e.getEstado());
                return true;
            }
        } catch (Exception ex) {

            Logger.getLogger(EmpleadoFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    //Funcion eliminar registro
    public void eliminarEmpleado() {
        try {

            //Se realiza consulta
            ce.eliminarEmpleado(txtIdentificacion.getText());

        } catch (Exception ex) {

            Logger.getLogger(EmpleadoFrm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    //Funcion actualizar empleado
    private void actualizarEmpleado() {
        try {

            //Se crea la clase para la consulta
            e = new Empleado("", txtCargo.getText(), txtEmailEmpresa.getText(), txtEstado.getText(),
                    txtNombre.getText(), txtApellido.getText(), txtTelefono.getText(), txtEmailPersona.getText(),
                    txtIdentificacion.getText());

            //Se realiza consulta
            ce.actualizarEmpleado(e);
        } catch (Exception ex) {

            Logger.getLogger(EmpleadoFrm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
