/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import clases.OrdenTrabajo;
import clases.Servicio;
import clases.UnidadComercial;
import control.ControlOrdenTrabajo;
import control.ControlServicio;
import control.ControlUnidadComercial;
import gestion.GestionServiciosSolicitados;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author teenc
 */
public class ordenTrabajoFrm extends javax.swing.JInternalFrame {

    ControlServicio cs = new ControlServicio();
    ControlUnidadComercial cuc = new ControlUnidadComercial();
    ControlOrdenTrabajo cot = new ControlOrdenTrabajo();
    DefaultTableModel tablaServ;
    Servicio s = null;
    UnidadComercial uc = null;
    OrdenTrabajo ot = null;
    ArrayList<Servicio> lista = new ArrayList<>();
    /**
     * Creates new form ordentrabajoFrm
     */
    
    public ordenTrabajoFrm() {
        initComponents();
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabalServicio = new javax.swing.JTable();
        txtNumOrden = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        cbxIdComercio = new javax.swing.JComboBox<>();
        cbxIdServicio = new javax.swing.JComboBox<>();
        btnAgrgarServ = new javax.swing.JButton();
        datCreacion = new com.toedter.calendar.JDateChooser();
        dateCierre = new com.toedter.calendar.JDateChooser();
        lblNombreComercio = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnNuevaOrden = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblNombreServi = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("N orden");

        jLabel2.setText("Estado");

        jLabel3.setText("Comercio");

        jLabel4.setText("Fecha Solicitud");

        jLabel5.setText("Fecha Vencimiento");

        jLabel6.setText("Servicios");

        jScrollPane3.setViewportView(tabalServicio);

        txtEstado.setEditable(false);
        txtEstado.setText("Abierto");

        cbxIdComercio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxIdComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIdComercioActionPerformed(evt);
            }
        });

        cbxIdServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxIdServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIdServicioActionPerformed(evt);
            }
        });

        btnAgrgarServ.setText("Agregar");
        btnAgrgarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrgarServActionPerformed(evt);
            }
        });

        lblNombreComercio.setText("jLabel7");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevaOrden.setText("Nuevo");
        btnNuevaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaOrdenActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblNombreServi.setText("jLabel8");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxIdComercio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(datCreacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dateCierre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNumOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbxIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNombreServi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreComercio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAgrgarServ, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 55, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevaOrden)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxIdComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreComercio)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(datCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dateCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgrgarServ)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreServi)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevaOrden)
                    .addComponent(btnEliminar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        listaServicios();
        listaComercio();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbxIdServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIdServicioActionPerformed
        cargarNombreServicio();
    }//GEN-LAST:event_cbxIdServicioActionPerformed

    private void btnAgrgarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrgarServActionPerformed
        try {
            s = cs.buscarServicio(cbxIdServicio.getSelectedItem().toString().toLowerCase());
            lista.add(s);            
            serviciosSolicitados(lista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAgrgarServActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        vaciarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbxIdComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIdComercioActionPerformed
        cargarnombreUnidadComercial();
    }//GEN-LAST:event_cbxIdComercioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarOt();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaOrdenActionPerformed
       nuevaOrden();
    }//GEN-LAST:event_btnNuevaOrdenActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      cot.eliminarOrdenTrabajo(txtNumOrden.getText());
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrgarServ;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevaOrden;
    private javax.swing.JComboBox<String> cbxIdComercio;
    private javax.swing.JComboBox<String> cbxIdServicio;
    private com.toedter.calendar.JDateChooser datCreacion;
    private com.toedter.calendar.JDateChooser dateCierre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblNombreComercio;
    private javax.swing.JLabel lblNombreServi;
    private javax.swing.JTable tabalServicio;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNumOrden;
    // End of variables declaration//GEN-END:variables

    public void serviciosSolicitados(ArrayList<Servicio> solicitados){
        try {
                tablaServ = new DefaultTableModel();
                String[] registro = new String[3];
                tablaServ.addColumn("Id Servicio");
                tablaServ.addColumn("Nombre");
                tablaServ.addColumn("Discripcion");
                for (Servicio s : solicitados) {
                    registro[0] = s.getIdServicio();
                    registro[1] = s.getNombreServicio();
                    registro[2] = s.getDescripcion();
                    tablaServ.addRow(registro);
                }    
                tabalServicio.setModel(tablaServ);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
}

    public void listaServicios(){
        try{
            cbxIdServicio.removeAllItems();
            ArrayList<Servicio> lista = cs.listaServicios();
            for (Servicio s : lista) {
                cbxIdServicio.addItem(s.getIdServicio().toLowerCase());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage()+" cbx ");
        }
    }

    private void cargarNombreServicio() {
        try {
            if(cbxIdServicio.getSelectedItem()!=null){
                s = cs.buscarServicio(cbxIdServicio.getSelectedItem().toString().toLowerCase());
                lblNombreServi.setText(s.getNombreServicio().toUpperCase());
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage()+" lb ");
        }
    }

    public void vaciarTabla(){
        try {
            if(tablaServ!=null){
                tabalServicio.getModel();
                tablaServ.setRowCount(0);
                lista.clear();
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void cargarnombreUnidadComercial() {
        try {
            if(cbxIdComercio.getSelectedItem()!=null){
                uc = cuc.buscarUnidadComercial(cbxIdComercio.getSelectedItem().toString().toLowerCase());
                lblNombreComercio.setText(uc.getNombreUnidadComercial().toLowerCase());
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage()+" lb ");
        }
    }
    
    public void listaComercio(){
        try{
            cbxIdComercio.removeAllItems();
            ArrayList<UnidadComercial> lista = cuc.listarUnidadComercial();
            for (UnidadComercial uc : lista) {
                cbxIdComercio.addItem(uc.getIdUnidadComercial().toLowerCase());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage()+" cbx ");
        }
    }

    private void buscarOt() {
        try {
            vaciarTabla();
            tablaServ = new DefaultTableModel();
            ot = cot.buscarOrdenTrabajo(txtNumOrden.getText().toLowerCase());
            txtNumOrden.setText(ot.getIdOrdenTrabajo());
            txtEstado.setText(ot.getEstado());
            cbxIdComercio.setSelectedItem(ot.getUnidadCo().getIdUnidadComercial().toLowerCase());
            lblNombreComercio.setText(ot.getUnidadCo().getNombreUnidadComercial().toLowerCase());
//            datCreacion.setDate(ot.getFechaSolicitud());
//            dateCierre.setDate(ot.getFechaCierre());
            ArrayList<Servicio> listaS;
            String[] registro = new String[3];
            tablaServ.addColumn("Id Servicio");
            tablaServ.addColumn("Servicio");
            tablaServ.addColumn("Descripcion");
            listaS = ot.getidServiciosSolicitados();
            for (Servicio sv : listaS) {
                registro[0] = sv.getIdServicio();
                registro[1] = sv.getNombreServicio();
                registro[2] = sv.getDescripcion();
                tablaServ.addRow(registro);
            }
            tabalServicio.setModel(tablaServ);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    
    } 

    private ArrayList<Servicio> listaServNuevo() {
        ArrayList<Servicio> listServ = new ArrayList<>();
        try {
            int rows = tablaServ.getRowCount();
            for (int i = 0; i < rows; i++) {
                String idServicio =String.valueOf(tabalServicio.getValueAt(i, 0));
                String nombre =String.valueOf(tabalServicio.getValueAt(i, 1));
                String descripcion =String.valueOf(tabalServicio.getValueAt(i, 2));
                Servicio s = new Servicio(idServicio, nombre, descripcion);
                listServ.add(s);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return listServ;
        
    }
    
    public void nuevaOrden(){
        try {
            ArrayList<Servicio> liSe = listaServNuevo();
            String idOrden = txtNumOrden.getText().toLowerCase();
            String estado = txtEstado.getText().toLowerCase();
            uc = cuc.buscarUnidadComercial(cbxIdComercio.getSelectedItem().toString().toLowerCase());
            String fSolicitud = "";
            String fCierre = "";
            ot = new OrdenTrabajo(idOrden, estado, uc, fSolicitud,
                    fCierre, liSe);
            cot.nuevoOrdenTrabajo(ot);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }
}
